### ISSUE TITLE
Trouble getting list of gists from Github Enterprise server

### ISSUE THREAD

**Issue by lwiechec** [defunkt/gist.el#100]
Hello,

I don't know what happened but gist.el stopped getting the list of gists from our GitHub Enterprise server.

The error message is:
```
Debugger entered--Lisp error: (wrong-type-argument listp [eieio-class-tag--gh-api-callback [eieio-class-tag--gh-cache "~/.emacs.d/var/pcache/gh/gh-gist-api/wiechec" nil "0.3/gh-3" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ()) gh-cache-entry 1479744793.186607 300] ("/users/wiechec/gists" "GET" "<REMOVED>") nil])
...
```

I tested the API by hand with curl and it works ok.

I was wondering if this is gist.el error or - more gh's API...

Any help will be appreciated!

Łukasz

**Comment by sigma** [comment]
This string: "0.3/gh-3" seems to indicate that you have fairly old versions of pcache.el and gh.el installed (or maybe the cache doesn't get refreshed for whatever reason).
I'd suggest to
- delete ~/.emacs.d/var/pcache
- update pcache.el and gh.el to latest version (melpa should have those)

let me know if that helps

**Comment by lwiechec** [comment]
Yann, thanks for the tip - I will check it tomorrow!!                                                                                                                                                                                                                                                                                                                                        Łukasz Wiecheć                                                                                                                                                                                                                 From: Yann HodiqueSent: Monday, 21 November 2016 18:54To: defunkt/gist.elReply To: defunkt/gist.elCc: Lukasz Wiechec; AuthorSubject: Re: [defunkt/gist.el] Trouble getting list of gists from Github Enterprise server (#100)This string: "0.3/gh-3" seems to indicate that you have fairly old versions of pcache.el and gh.el installed (or maybe the cache doesn't get refreshed for whatever reason).
I'd suggest to

delete ~/.emacs.d/var/pcache
update pcache.el and gh.el to latest version (melpa should have those)

let me know if that helps

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/defunkt/gist.el","title":"defunkt/gist.el","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/defunkt/gist.el"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sigma in #100: This string: \"0.3/gh-3\" seems to indicate that you have fairly old versions of pcache.el and gh.el installed (or maybe the cache doesn't get refreshed for whatever reason).\r\nI'd suggest to\r\n- delete ~/.emacs.d/var/pcache\r\n- update pcache.el and gh.el to latest version (melpa should have those)\r\n\r\nlet me know if that helps"}],"action":{"name":"View Issue","url":"https://github.com/defunkt/gist.el/issues/100#issuecomment-262014932"}}}

**Comment by lwiechec** [comment]
@sigma indeed, upgrading the gh package helped. Thanks for the tip!
