### ISSUE TITLE
Editing description on non-cached gist makes the gist empty

### ISSUE THREAD

**Issue by alpha22jp** [defunkt/gist.el#101]
Steps to replicate

1. Create new gist by `M-x gist-buffer`.
2. `M-x gist-list` and edit description on the gist created by step 1.

I guess this is caused by updating the gist with empty title and content, bacause they aren't retrieved yet.

**Comment by sigma** [comment]
sorry about that, I should have been more careful merging that code.

@rothmichaels can you explain the original intention?
https://github.com/sigma/gh.el/blob/master/gh-gist.el#L95 is the reason why setting `files` to `nil` should just do the right thing (and is invisibile to the API)

**Comment by rothmichaels** [comment]
@sigma I believe this was related to some bugs I was having changing the name or description of a Gist (I forget if this was all Gists, or a more specialized bug—e.g. maybe it was only private gists or something)

See sigma/gh.el#64 and #74 for more info.

I believe the change in 9baace6 will not work correctly if you don't also have the change from sigma/gh.el#64

I will take a look at this in more detail Monday or Tuesday.

Also, I do recall when I was working on this being confused about the difference between _master_ and _next_ branches.

**Comment by sigma** [comment]
@rothmichaels ok, thanks. The situation is simpler now, as the `next` branch has been merged into `master` some time back (which implies sigma/gh.el#64 is there too)
