### ISSUE TITLE
Setting auth information explicitly with emacs variable

### ISSUE THREAD

**Issue by therockmandolinist** [defunkt/gist.el#102]
I'm not convinced I should have to store auth info in a gitconfig file - it would be nice to have the option to provide it directly with a set of variables (something like gist-username, gist-token).

**Comment by sigma** [comment]
you can already do that by customizing variable `gh-profile-alist` and using fields `:username` and `:token`

**Comment by therockmandolinist** [comment]
Oh, cool - what's the recommended way to do this in elisp (i.e. without customize)? I want to get my token like this so as to not have to store it in plain text: `:token (password-store-get "my/github/token)"`

**Comment by therockmandolinist** [comment]
Ah, nevermind - I was able to setf it.
