### ISSUE TITLE
gist-print-current-url from within the gist ?

### ISSUE THREAD

**Issue by dotemacs** [defunkt/gist.el#103]
Hi

I can see that `gist-print-current-url` https://github.com/defunkt/gist.el/blob/a03f142455e8b39f77fbd57ee1c1e44478c1f9e2/gist.el#L545 
prints & adds to the kill-ring the URL of the current gist URL. But that only works if you're in the `gist-list` buffer.

Would you be open to having a function that could obtain the current gist's URL when you're in a buffer of a file that is part of a given gist? Either creating a new function or enhancing this exiting function `gist-print-current-url`? 

Thanks

**Comment by sigma** [comment]
I've extended `gist-current-url` to do the right thing in gist buffers, so the existing function should now just work.

Thanks !
