### ISSUE TITLE
gist-list or gist-buffer Fail with "void-function marshal-get-class-slot"

### ISSUE THREAD

**Issue by kevinbirch** [defunkt/gist.el#106]
I'm using gist.el version `20170604.1834` from MELPA on Mac OS using "25.3.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29)) of 2017-09-19" from homebrew.

I've put the [backtrace in a gist](https://gist.github.com/kevinbirch/48754edcb93860ba418f74b085b6ad07)

**Comment by sigma** [comment]
I think that might happen after updating `marshal.el` to something like 0.8.2 and before restarting Emacs. 
At this point, the new method would not exist for the already defined classes.

Please reopen if a restart doesn't help.

Thanks !

**Comment by kevinbirch** [comment]
seems to be working, thanks!
