### ISSUE TITLE
gist-add-buffer fails with (invalid-slot-type gh-gist-gist id string nil)

### ISSUE THREAD

**Issue by suhailshergill** [defunkt/gist.el#43]
emacs-version: GNU Emacs 24.1.1 (x86_64-pc-linux-gnu, GTK+ Version 2.24.12) of 2012-09-22 on batsu, modified by Debian

backtrace:

Debugger entered--Lisp error: (invalid-slot-type gh-gist-gist id string nil)
  signal(invalid-slot-type (gh-gist-gist id string nil))
  (if (or (null num) (zerop num)) (signal (car err) (cdr err)) (oset req :num-retries (1- num)) (gh-url-run-request req resp))
  (let ((num (oref req :num-retries))) (if (or (null num) (zerop num)) (signal (car err) (cdr err)) (oset req :num-retries (1- num)) (gh-url-run-request req resp)))
  (condition-case err (progn (oset resp :-req req) (gh-url-response-init resp (current-buffer))) (error (let ((num (oref req :num-retries))) (if (or (null num) (zerop num)) (signal (car err) (cdr err)) (oset req :num-retries (1- num)) (gh-url-run-request req resp)))))
  (let\* ((--cl-rest-- req-resp) (req (if (= (length --cl-rest--) 2) (pop --cl-rest--) (signal (quote wrong-number-of-arguments) (list nil (length --cl-rest--))))) (resp (car --cl-rest--))) (condition-case err (progn (oset resp :-req req) (gh-url-response-init resp (current-buffer))) (error (let ((num (oref req :num-retries))) (if (or (null num) (zerop num)) (signal (car err) (cdr err)) (oset req :num-retries (1- num)) (gh-url-run-request req resp))))))
  (progn (let\* ((--cl-rest-- req-resp) (req (if (= (length --cl-rest--) 2) (pop --cl-rest--) (signal (quote wrong-number-of-arguments) (list nil (length --cl-rest--))))) (resp (car --cl-rest--))) (condition-case err (progn (oset resp :-req req) (gh-url-response-init resp (current-buffer))) (error (let ((num (oref req :num-retries))) (if (or (null num) (zerop num)) (signal (car err) (cdr err)) (oset req :num-retries (1- num)) (gh-url-run-request req resp)))))))
  (destructuring-bind (req resp) req-resp (condition-case err (progn (oset resp :-req req) (gh-url-response-init resp (current-buffer))) (error (let ((num (oref req :num-retries))) (if (or (null num) (zerop num)) (signal (car err) (cdr err)) (oset req :num-retries (1- num)) (gh-url-run-request req resp))))))
  gh-url-set-response(nil ([object gh-api-paged-request "gh-api-paged-request" "PATCH" "https://api.github.com/gists/BAR" nil (("Authorization" . "token FOO") ("Content-Type" . "application/json")) "{\"description\":\".gitattributes gpg smudge\/clean filter\", \"public\":null, \"files\":{\"\/home\/shergill\/config\/.git\/modules\/arcana\/info\/attributes\":{\"filename\":\"\/home\/shergill\/config\/.git\/modules\/arcana\/info\/attributes\", \"content\":\"\* filter=gpg diff=gpg\n[merge]\n    renormalize=true\n\"}}}" nil 0] [object gh-api-paged-response "gh-api-paged-response" nil nil (("Content-Length" . "152") ("X-Content-Type-Options" . "nosniff") ("X-GitHub-Media-Type" . "github.beta") ("X-Accepted-OAuth-Scopes" . "gist") ("X-OAuth-Scopes" . "user, repo, gist") ("X-RateLimit-Remaining" . "4961") ("X-RateLimit-Limit" . "5000") ("Status" . "422 Unprocessable Entity") ("Connection" . "keep-alive") ("Content-Type" . "application/json; charset=utf-8") ("Date" . "Mon, 18 Mar 2013 04:52:07 GMT") ("Server" . "GitHub.com") (status-string . "Unprocessable Entity") (status-code . "422") (status-version . "1.1")) 422 nil (closure (t) (&rest args) (apply (quote gh-object-read) (quote gh-gist-gist) args)) [object gh-api-paged-request "gh-api-paged-request" "PATCH" "https://api.github.com/gists/BAR" nil (("Authorization" . "token FOO") ("Content-Type" . "application/json")) "{\"description\":\".gitattributes gpg smudge\/clean filter\", \"public\":null, \"files\":{\"\/home\/shergill\/config\/.git\/modules\/arcana\/info\/attributes\":{\"filename\":\"\/home\/shergill\/config\/.git\/modules\/arcana\/info\/attributes\", \"content\":\"\* filter=gpg diff=gpg\n[merge]\n    renormalize=true\n\"}}}" nil 0]]))
  #[(req &optional resp) "\306\307\"\306\310\"\306\311\"\306\312\"\306\313\"\211\203

**Comment by DinoChiesa** [comment]
Me too.  What was the problem?

**Comment by suhailshergill** [comment]
i believe i had stale byte-compiled files lying around
