### ISSUE TITLE
All gist functions result in: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by goodevilgenius** [defunkt/gist.el#61]
I just installed gist via marmalade on Emacs 24.3.1 on Windows 7. I ran the function `gist-list` and it gave the error `Wrong type argument: stringp, nil`. I tried several other gist- functions, all with the same result. It didn't ask for a username or password.

**Comment by cb0** [comment]
I'm still unale to use it. That's the detail error, maybe someone can see some what's wrong.
```bash
Contacting host: api.github.com:443
Opening TLS connection to `api.github.com'...
Opening TLS connection with `gnutls-cli --insecure -p 443 api.github.com'...failed
Opening TLS connection with `gnutls-cli --insecure -p 443 api.github.com --protocols ssl3'...failed
Opening TLS connection with `openssl s_client -connect api.github.com:443 -no_ssl2 -ign_eof'...done
Opening TLS connection to `api.github.com'...done
byte-code: Wrong type argument: listp, "https://developer.github.com/v3"
```

**Comment by axionix** [comment]
I get this error:
byte-code: Wrong type argument: listp, "https://developer.github.com/v3"
with emacs 24.5 using latest MELPA package and dependencies.

**Comment by Emantor** [comment]
I fixed it by moving the gitconfig entry for `token` to `token-oauth`, I think the github blog entry which is referenced in the Readme is way to old (from 2008...) and the config sytnax has changed now.

**Comment by torgeir** [comment]
Seeing the same thing as @axionix, on 24.5 with latest off melpa

**Comment by rgrinberg** [comment]
Same problem here.
