### ISSUE TITLE
Can't get gist.el to work behind a proxy 

### ISSUE THREAD

**Issue by smaret** [defunkt/gist.el#64]
I can't get gist.el to work behind my university proxy. In my `emacs.el`, I have set the `url-proxy-service` variable as follows:

``` lisp
(setq url-proxy-services '(("http" . "proxy.myuniversity.fr:3128")))
```

When I run `M-x gist-list` in Emacs, it displays the following message:

```
Opening TLS connection with `gnutls-clu --insecure -p 443 api.github.com`
```

and after a few moments:

```
Could not create connection to api.github.com:443
```

**Comment by Bost** [comment]
Bumped to this problem too :(
But think it has nothing to do with proxy.

**Comment by tripleee** [comment]
There are multiple scenarios.  For proper troubleshooting, more details would be necessary, or at least useful.

If your organization blocks outbound traffic to port 443, you probably need to connect via their proxy.  But does the proxy support HTTPS?  This is often not the case.  Can you connect to Github with (say) `echo "GET https://api.github.com/ HTTP/1.0" | openssl s_client -quiet -crlf -connect proxy:port`?  (Where `port` can be 3128, 443, 80, or a number of other things, depending.)

**Comment by Yevgnen** [comment]
Any news ?
