### ISSUE TITLE
prompt for gist description and name? 

### ISSUE THREAD

**Issue by yitang** [defunkt/gist.el#69]
Hi,

By default `gist-reigon-or-buffer` will use the buffer name as gist name, and there is no gist descriptions. I wonder if we could add prompts for input a) gist name and b) gist description, and this feature will make the gist management a lot easier. 

-Yi

**Comment by stig** [comment]
+1

**Comment by marcelino-m** [comment]
For gist description you can customize  var **gist-ask-for-description**:
```
(setq gist-ask-for-description t)
```
For gist name, I working on this #98

**Comment by sigma** [comment]
code has been merged
