### ISSUE TITLE
Error in latest emacs devel

### ISSUE THREAD

**Issue by dvhansen** [defunkt/gist.el#73]
Looking at the backtrace I refuse to investigate myself, but maybe someone is interested in it.  Might be a gh.el error, but as I said, I won't touch it.

Run $ emacs -Q and eval

``` emacs-lisp
(package-initialize)
(toggle-debug-on-error)
;; Otherwise we get some recursive loading error.
(require 'jka-compr)
;; Load the source for a less ugly backtrace.
(setq load-suffixes '(".el"))
(gist-list)
```

```
(wrong-number-of-arguments (lambda (api newname &rest args) (let ((gh-api-v3-authenticator (quote gh-oauth-password-authenticator))) (call-next-method))) 1) 
[...]
```

**Comment by sigma** [comment]
actually it's a relatively simple one :)

problem is in gh-oauth.el:
```lisp
(defmethod constructor :static ((api gh-oauth-api) newname &rest args)
  ;; force password authentication for this API
  (let ((gh-api-v3-authenticator 'gh-oauth-password-authenticator))
    (call-next-method)))
```

Looks like eieio changed, and removed the `newname` argument in object constructor...
At this point, I'm not sure how to write backward-compatible code

**Comment by sigma** [comment]
actually I just compiled emacs from git master (as of 9/5/2015), installed fresh packages, and it just works.
There seems to have been such a problem earlier this year, but it's been fixed. So you might want to update your emacs.

**Comment by dvhansen** [comment]
Any idea what I could be doing wrong?
```emacs-lisp
(emacs-version)
"GNU Emacs 25.0.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.6)
 of 2015-09-05"
(package-initialize)
(eieio-version)
"1.4"
(gist-list)
```
`*Backtrace*` buffer pops up:
```emacs-lisp
(wrong-number-of-arguments #[(api newname &rest args) [...]
```

**Comment by sigma** [comment]
hmm, let me reopen it for the time being. I might be missing something obvious, and in any case I should probably revisit some of the code in gh.el since quite a few things have been deprecated even though they're supposedly backward-compatible for now

**Comment by sigma** [comment]
everything seems to work fine on 25.1.1 these days, so we should be good
