### ISSUE TITLE
edit description fails with `byte-code: Invalid slot type: gh-gist-gist, id, string, nil`

### ISSUE THREAD

**Issue by stig** [defunkt/gist.el#74]
Creating gist worked beautifully, but attempting to edit the description from the `gist-list` did not work. I'm getting this sequence of messages:

```
Contacting host: api.github.com:443
Opening TLS connection to `api.github.com'...
Opening TLS connection with `gnutls-cli --insecure -p 443 api.github.com'...done
Opening TLS connection to `api.github.com'...done
byte-code: Invalid slot type: gh-gist-gist, id, string, nil
```

My Emacs: 
```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org
```

I just installed `gist.el` from melpa today (version 20150906.954).

**Comment by alphapapa** [comment]
Same here.  Emacs 24.4.1.  Just installed `gist.el` a few minutes ago.

**Comment by axionix** [comment]
Same here as well.

**Comment by rothmichaels** [comment]
:+1:

**Comment by rothmichaels** [comment]
This same error is happening with `gist-mode-write-file`.

**Comment by rothmichaels** [comment]
Looks like I found the bug in *gh-gist.el*; see pull request above.

**Comment by zilongshanren** [comment]
@rothmichaels  
I still got this issue when doing gist-edit-current-description...

**Comment by rothmichaels** [comment]
@zilongshanren I wonder if this relates to the version of gh.el or Emacs. 

Are you trying this from a gist buffer or the _\*github:gists\*_ buffer? `gist-edit-current-description` works for me when used from _\*github:gists\*_ (if I call it from a gist buffer, I get the error `user-error: Can't edit a gist that doesn't belong to you`).

I am using:
- Emacs.app (from MacPorts): _GNU Emacs 24.5.1 (x86_64-apple-darwin15.4.0, NS apple-appkit-1404.46)_
- defunkt/gist.el@88d0e5be77fefad9fe1413505a80bdac7a9e7361
- sigma/gh.el@d0471dd1ba279072cbf8caf6368f3008d7120f25
