### ISSUE TITLE
Error with gist-list

### ISSUE THREAD

**Issue by saptarshiguha** [defunkt/gist.el#76]
Installed via marmalade,

if: Wrong type argument: listp, "https://developer.github.com/v3"

when M-x gist-list is called.

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

**Comment by alphapapa** [comment]
Is this still happening?  It works for me now.

**Comment by NgaNguyenDuy** [comment]
I got same issue. I have no ideal for it although i was try to google many time but nothing.

**Comment by peschkaj** [comment]
Running into the same issue with gist version `20160118.1656` and emacs 24.5.1 on Ubuntu 16.04 LTS (`GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2016-04-17 on lgw01-04, modified by Debian`).

**Comment by peschkaj** [comment]
I solved my problem by:

1. Disabling emacs as a daemon
2. Using `package-list-packages` and deleting both `gh` and `gist`
3. Exit emacs
4. Reboot
5. Manually start emacs.
6. Re-enable emacs as a daemon.

**Comment by sigma** [comment]
I added some additional safeguards in `pcache.el` to try and prevent those situations (basically the cache can become unreadable when `eieio` introduces incompatible changes, so I try to detect that and purge the cache then)
