### ISSUE TITLE
Permit uploading and reading of gists from github enterprise installation

### ISSUE THREAD

**Issue by vxe** [defunkt/gist.el#80]
I would like to use gist.el with enterprise github.  The default behavior appears to read and upload gists to github.com.  I do not see a configuration option exposed in 'customize-group'.  I would like to point gist.el to my enterprise github installation as is done here https://github.com/defunkt/gist 

Setting GITHUB_URL like this does not appear to work

```
(setenv "GITHUB_URL" "https://GITHUB_ENT_URL")
```

The following change to ~/.gitconfig doesn't work as it attempts to make a connection to api.github.com with my enterprise login name and fails

```
[github]

    url = GITHUB_ENT_URL
```

**Comment by vxe** [comment]
gitconfig typ

**Comment by vxe** [comment]
one more typo

**Comment by corpix** [comment]
Hi. gist.el uses gh api module for emacs. But readme of this projects does not describe how to use this extensions with github enterprise. Probably this comment in issue could help you https://github.com/sigma/gh.el/issues/12#issuecomment-14971939

**Comment by sigma** [comment]
Yes, it should just work. Use something like this:

```lisp
(eval-after-load 'gh-profile
  '(add-to-list 'gh-profile-alist
    `("work" :url "https://ghe.work/api/v3"
      :remote-regexp ,(gh-profile-remote-regexp "ghe.work"))))
```
