### ISSUE TITLE
Show gist name in *github:gists* buffer

### ISSUE THREAD

**Issue by xged** [defunkt/gist.el#82]

**Comment by sigma** [comment]
@xged not sure I understand the request. What exactly would you like shown that's not there?

**Comment by itkach** [comment]
Gists don't have "names", but they have files and files do have names. If gist description is omitted (which is quite often) you see something like this:
```
6b4fe43... 02/01/15 20:55       public 
```
which is not nearly as useful as something like
```
6b4fe43... mathjax-perf.org 02/01/15 20:55       public 
```
where mathjax-perf.org is the name of the single file in this gist. gists containing multiple files are trickier but any method to show them - truncated list, name of first file (maybe with total file count), full-list on a separate line - would still be a useful improvement.

**Comment by itkach** [comment]
Looks like Github's web UI uses name of the first added files as gist name

**Comment by sigma** [comment]
you can customize the display with something like

```lisp
(setq gist-list-format
      '((id "Id" 10 nil identity)
        (created "Created" 20 nil "%D %R")
        (visibility "Visibility" 10 nil
         (lambda
             (public)
           (or
            (and public "public")
            "private")))
        (description "Description" 60 nil identity)
        (files "Files" 0 nil
         (lambda
             (files)
           (mapconcat 'identity files ", ")))))
```

**Comment by kaushalmodi** [comment]
Thanks @sigma.

Here's a variant of that.. At first I was confused why that `gist-list-format` value did not work.. Then I realized that that was because the *Description* column was too wide for my screen and so the *Files* column ended up being 'hidden'.

```
(setq gist-list-format
      '((created "Created" 15 nil "%D %R")
        (id "Id" 10 nil identity)
        (files "Files" 35 nil (lambda (files)
                                (mapconcat 'identity files ", ")))
        (visibility "Private" 8 nil (lambda (public)
                                      (or (and public "") "   Y")))
        (description "Description" 0 nil identity)))
```
