### ISSUE TITLE
When javascript gist is opened from gist-list evil mode is disabled and can't be enabled in resulting buffer

### ISSUE THREAD

**Issue by michaelmrose** [defunkt/gist.el#83]
GNU Emacs 24.5.1 on Funtoo Linux current with emacs running in server mode via --daemon and emacsclient -c.

If there is any other info I can provide feel free to ask

**Comment by michaelmrose** [comment]
Confimed this happens on 25.0.92.1 and with or without daemon. Also you can reenable evil working properly by running javascript-mode but this kills the gist functionality.

**Comment by sigma** [comment]
@michaelmrose can you provide steps to reproduce? I'm not an evil-mode user so this is a little bit of an uncharted territory for me. Thanks !

**Comment by michaelmrose** [comment]
Will provide this when I get back to my computer later tonight.
