### ISSUE TITLE
Storing passwords in plaintext??

### ISSUE THREAD

**Issue by siassaj** [defunkt/gist.el#84]
So i just used this to successfully make a gist, but it appears to have saved my password in plaintext in ~/.gitconfig.

Is this correct?

**Comment by thiderman** [comment]
I just saw this as well. However, since neither `password`, `pass` or `config` appear in the source it could be that it is some underlying library that causes this.

**Comment by thiderman** [comment]
Submitted to upstream plugin.

**Comment by sigma** [comment]
should be fixed now
