### ISSUE TITLE
Gist Created, Error with Retrieving URL within Emacs

### ISSUE THREAD

**Issue by NLisa** [defunkt/gist.el#92]
I have the following error when attempting to call `gist-buffer` or `gist-region`

The gist is correctly created, however the URL is not returned and fails with the following error.

[Successfully created gist](https://gist.github.com/NLisa/ac2d7027d6d653d1a2916538c77f46a6#file-messages-txt)

Contacting host: api.github.com:443
apply: Wrong type argument: symbolp, [eieio-class-tag--gh-gist-gist unbound unbound unbound nil unbound unbound unbound unbound unbound ...]

Thank you.

**Comment by squiter** [comment]
Same here!

**Comment by mrwacky42** [comment]
When I use `gist-buffer-private` or `gist-region-private`, I get:

`eieio-oref: Wrong type argument: (or eieio-object class), nil, obj`

But it does create the gist, just no longer puts it in the kill ring. eieio is dark magic to me. I'm not sure how to debug.

**Comment by sigma** [comment]
so typically those cryptic errors complaining about broken vectors is due to files compiled with older emacs loaded in newer emacs. eieio has like 0 backward-compatibility when it comes to compiled stuff :(
I suggest uninstalling/reinstalling gh.el and gist.el (and potentially marshal.el)

**Comment by mrwacky42** [comment]
@sigma - Right you are. I tried deleting *most* of my elpa directory, and reinstalling gh.el, gist.el, and some others.  But now I've nuked the entire tree and let `package-install` do its magic. And I can get gist urls again.  Good times. I love this package.

**Comment by sigma** [comment]
tentatively closing

**Comment by NLisa** [comment]
This can be closed. I confirm that flushing the elpa folder and re-installing fixed the issues I was having.

Thank you
