### ISSUE TITLE
Error "Multibyte text in HTTP request" occurs when code snippet contains non-ASCII characters

### ISSUE THREAD

**Issue by lululau** [defunkt/gist.el#94]
When use `gist-region` to create gist, this error occurs if selected region contains non-ASCII characters

Emacs Version: 25.1

**Comment by szabolcs-szilagyi** [comment]
I have had this error when wanted to upload buffer:
```
error in process sentinel: Multibyte text in HTTP request: POST /gists HTTP/1.1
MIME-Version: 1.0
Connection: keep-alive
Extension: Security/Digest Security/SSL
Host: api.github.com
Accept-encoding: gzip
Accept: */*
User-Agent: URL/Emacs
Authorization: token XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Type: application/json
Content-length: 19583
```
the content of my gist would have been my full `.spacemacs` file. So an easy way to reproduce is to try to post that file.

**Comment by sigma** [comment]
should be fixed now. Thanks !
